### ISSUE TITLE
Docker empty response error

### ISSUE THREAD

**Issue by RaminMT** [ahmdrz/instagraph#1]
Hi
I pulled & started an instance of instagraph in docker but when I try to access the web on 8080 port I face with a `ERR_EMPTY_RESPONSE`

**Comment by ahmdrz** [comment]
Hi
You have to wait until program start listening on 8080. It might take long.
Please send instagraph's log.

**Comment by RaminMT** [comment]
I double checked that and same result.
But made a little work around & found if in `main.go` you change `"localhost:8080"` to `"0.0.0.0:8080"` that makes sense

Anyway thank you

**Comment by ahmdrz** [comment]
You're right.
Can you make a PR for it ?
It's better to get listening address from CLI.

**Comment by RaminMT** [comment]
Yes, sure I can and I will.
